version: 0.0
os: linux

# Define which files should be copied and where
files:
  - source: /
    destination: /opt/viewpost
    overwrite: true

# Set proper permissions for the application files
permissions:
  - object: /opt/viewpost
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

# Define deployment lifecycle event hooks
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root