version: 0.0
os: linux

# File copying instructions
files:
  - source: /
    destination: /opt/viewpost
    overwrite: true

# Unified permissions section
permissions:
  # Base directory permissions
  - object: /opt/viewpost
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file

  # Specific script permissions
  - object: /opt/viewpost/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

  # Log directory permissions
  - object: /var/log/viewpost
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

# Deployment lifecycle hooks
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root