version: 0.2

phases:
  build:
    commands:
      - echo "Running security checks..."
      - pip install safety bandit
      - safety check
      - bandit -r ./app -f json -o security-report.json
      
reports:
  security_report:
    files:
      - security-report.json
    file-format: JSON

artifacts:
  files:
    - security-report.json
    - '**/*'