version: 0.2

phases:
  build:
    commands:
      - echo "Running security checks..."
      - pip install safety bandit
      - safety check --output json > safety-report.json || true
      - bandit -r ./ -f json -o bandit-report.json || true
      
reports:
  security-report:
    files:
      - "safety-report.json"
      - "bandit-report.json"
    file-format: JSON

artifacts:
  files:
    - safety-report.json
    - bandit-report.json
    - '**/*'