# buildspec-build.yml
version: 0.2

phases:
  build:
    commands:
      - echo "Starting build phase"
      - echo "Preparing application files..."
      - mkdir -p build
      - cp -r app/* build/
      - cp requirements.txt build/
      - cp appspec.yml build/
      - cp -r scripts build/

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  name: BuildOutput