version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing system dependencies..."
      - yum update -y
      - yum install -y python3-devel gcc python3-psutil
      
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install pytest flask psutil werkzeug==2.0.1
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

artifacts:
  files:
    - '**/*'
  base-directory: '.'

cache:
  paths:
    - '/root/.cache/pip'