version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing test dependencies..."
      - pip install Flask==2.0.1 psutil==5.8.0 werkzeug==2.0.1 pytest==7.0.1 pytest-cov==3.0.0
      
  build:
    commands:
      - echo "Running tests..."
      - cd app
      - python -m pytest -v

artifacts:
  files:
    - '**/*'
  base-directory: '.'