AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for static asset storage.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${AWS::Region}-pipeline-artifacts"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: PipelineArtifactsBucket
        - Key: Environment
          Value: Production

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
